Fix CI for new setup

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,101 +25,82 @@ jobs:
       # ^ not in base
 
       - uses: actions/checkout@master
-        id: checkout-fstar
-        with:
-          path: FStar
-          repository: FStarLang/FStar
-          ref: master
+
+      - name: Checkout submodules
+        run: |
+          git submodule init
+          git submodule update --depth 1
+
+      - name: Read commit hashes for submodules
+        id: hashes
+        run: |
+          H=$(git -C opt/FStar rev-parse HEAD)
+          echo "FSTAR_COMMIT=$H" >> "$GITHUB_OUTPUT"
+          H=$(git -C opt/karamel rev-parse HEAD)
+          echo "KARAMEL_COMMIT=$H" >> "$GITHUB_OUTPUT"
+          H=$(git -C opt/pulse rev-parse HEAD)
+          echo "PULSE_COMMIT=$H" >> "$GITHUB_OUTPUT"
 
       - name: Try fetch built F*
         id: cache-fstar
         uses: actions/cache/restore@v4
         with:
-          path: FStar
-          key: FStar-${{ runner.os }}-${{ runner.arch }}-${{ steps.checkout-fstar.outputs.commit }}
+          path: opt/FStar
+          key: FStar-${{ runner.os }}-${{ runner.arch }}-${{ steps.hashes.outputs.FSTAR_COMMIT }}
 
       - name: Build F*
         if: steps.cache-fstar.outputs.cache-hit != 'true'
         run: |
-          make -C FStar -sj$(nproc) ADMIT=1
+          make -C opt FStar -sj$(nproc)
 
       - name: Save built F*
         if: steps.cache-fstar.outputs.cache-hit != 'true'
         uses: actions/cache/save@v4
         with:
-          path: FStar
-          key: FStar-${{ runner.os }}-${{ runner.arch }}-${{ steps.checkout-fstar.outputs.commit }}
-
-      - run: echo "FSTAR_HOME=$(pwd)/FStar" | sudo tee -a $GITHUB_ENV
-      - run: echo "FSTAR_EXE=$(pwd)/FStar/bin/fstar.exe" | sudo tee -a $GITHUB_ENV
-      - run: echo "$(pwd)/FStar/bin" | sudo tee -a $GITHUB_PATH
-      # FSTAR_HOME just for compat. *Either* of the other two should suffice, eventually.
-
-      - uses: actions/checkout@master
-        id: checkout-karamel
-        with:
-          path: karamel
-          repository: FStarLang/karamel
-          ref: master
+          path: opt/FStar
+          key: FStar-${{ runner.os }}-${{ runner.arch }}-${{ steps.hashes.outputs.FSTAR_COMMIT }}
 
       - name: Try fetch built karamel
         id: cache-karamel
         uses: actions/cache/restore@v4
         with:
-          path: karamel
-          key: karamel-${{ runner.os }}-${{ runner.arch }}-${{ steps.checkout-fstar.outputs.commit }}-${{ steps.checkout-karamel.outputs.commit }}
+          path: opt/karamel
+          key: karamel-${{ runner.os }}-${{ runner.arch }}-${{ steps.hashes.outputs.FSTAR_COMMIT }}-${{ steps.hashes.outputs.KARAMEL_COMMIT }}
 
       - name: Build karamel (if not cached)
         if: steps.cache-karamel.outputs.cache-hit != 'true'
         run: |
-          make -C karamel -sj$(nproc) ADMIT=1
+          make -C opt karamel -sj$(nproc)
 
       - name: Save built karamel
         if: steps.cache-karamel.outputs.cache-hit != 'true'
         uses: actions/cache/save@v4
         with:
-          path: karamel
-          key: karamel-${{ runner.os }}-${{ runner.arch }}-${{ steps.checkout-fstar.outputs.commit }}-${{ steps.checkout-karamel.outputs.commit }}
-
-      - run: echo "KRML_HOME=$(pwd)/karamel" | sudo tee -a $GITHUB_ENV
-      - run: echo "KRML_EXE=$(pwd)/karamel/krml" | sudo tee -a $GITHUB_ENV
-      - run: echo "$(pwd)/karamel" | sudo tee -a $GITHUB_PATH
-
-      - uses: actions/checkout@master
-        id: checkout-pulse
-        with:
-          path: pulse
-          repository: FStarLang/pulse
-          ref: main
+          path: opt/karamel
+          key: karamel-${{ runner.os }}-${{ runner.arch }}-${{ steps.hashes.outputs.FSTAR_COMMIT }}-${{ steps.hashes.outputs.KARAMEL_COMMIT }}
 
       - name: Try fetch built pulse
         id: cache-pulse
         uses: actions/cache/restore@v4
         with:
-          path: pulse
-          key: pulse-${{ runner.os }}-${{ runner.arch }}-${{ steps.checkout-fstar.outputs.commit }}-${{ steps.checkout-pulse.outputs.commit }}
+          path: opt/pulse
+          key: pulse-${{ runner.os }}-${{ runner.arch }}-${{ steps.hashes.outputs.FSTAR_COMMIT }}-${{ steps.hashes.outputs.PULSE_COMMIT }}
 
       - name: Build pulse (if not cached)
         if: steps.cache-pulse.outputs.cache-hit != 'true'
         run: |
-          make -C pulse -sj$(nproc) ADMIT=1
+          make -C opt pulse -sj$(nproc)
 
       - name: Save built pulse
         if: steps.cache-pulse.outputs.cache-hit != 'true'
         uses: actions/cache/save@v4
         with:
-          path: pulse
-          key: pulse-${{ runner.os }}-${{ runner.arch }}-${{ steps.checkout-fstar.outputs.commit }}-${{ steps.checkout-pulse.outputs.commit }}
-
-      - run: echo "PULSE_HOME=$(pwd)/pulse"/out | sudo tee -a $GITHUB_ENV
-
-      - uses: actions/checkout@master
-        with:
-          path: everparse
+          path: opt/pulse
+          key: pulse-${{ runner.os }}-${{ runner.arch }}-${{ steps.hashes.outputs.FSTAR_COMMIT }}-${{ steps.hashes.outputs.PULSE_COMMIT }}
 
       - name: Everparse CI
         id: cistep
-        run: . $HOME/.cargo/env && make -C everparse ci -skj$(nproc)
+        run: . $HOME/.cargo/env && make ci -skj$(nproc)
 
       # I'm leaving this disabled as I do not get good incrementality
       # when trying this out by hand due to dependence hash mismatches
@@ -159,9 +140,12 @@ jobs:
             Status: ${{ steps.cistep.outcome == 'success' && '✅' || steps.cistep.outcome == 'cancelled' && '⚠' || '❌' }} ([link](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}))
             Elapsed time: ${{ steps.duration.outputs.duration }}
 
-  # No-op job for branch protection.
+  # Branch protection points here.
   ciok:
     runs-on: ubuntu-latest
     needs: ci
+    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
     steps:
-      - run: exit 0
+      # Note: we only run on failure. Otherwise this is skipped, which counts
+      # as a success.
+      - run: exit 1
